// Generated by CoffeeScript 1.3.3
(function() {
  var Watcher, _;

  _ = require('underscore');

  Watcher = require('./watcher');

  module.exports = function(schema, pluginOpts) {
    var index;
    if (pluginOpts == null) {
      pluginOpts = {};
    }
    pluginOpts = _.defaults({}, pluginOpts, {
      interval: 1000,
      path: 'state',
      query: {},
      sort: {},
      select: {},
      autoIndex: true
    });
    if (pluginOpts.autoIndex) {
      index = {};
      index[pluginOpts.path] = 1;
      _.extend(index, pluginOpts.sort);
      schema.index(index);
    }
    return schema.statics.poll = function(from, to, opts, callback) {
      var checker, query, queryOptions, update, watcher,
        _this = this;
      if (opts == null) {
        opts = {};
      }
      if (_.isFunction(opts)) {
        callback = opts;
        opts = {};
      }
      opts = _.defaults({}, opts, pluginOpts);
      if (!_.isFunction(callback)) {
        throw new Error('callback should be a function');
      }
      query = function() {
        var q, _ref;
        q = _.clone((_ref = typeof opts.query === "function" ? opts.query() : void 0) != null ? _ref : opts.query);
        q[opts.path] = from;
        return q;
      };
      update = {};
      update[opts.path] = to;
      queryOptions = {
        upsert: false,
        "new": true,
        sort: opts.sort,
        select: opts.select
      };
      checker = function(cb) {
        return _this.findOneAndUpdate(query(), update, queryOptions, cb);
      };
      watcher = new Watcher(checker, opts.interval);
      watcher.on('data', function(doc) {
        return callback.call(doc, doc);
      });
      watcher.start();
      return watcher;
    };
  };

}).call(this);
